#
# Copyright INK Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#
version: '2'

services:

  ca.org1.example.com:
    image: inklabsfoundation/inkchain-ca
    environment:
      - INKCHAIN_CA_HOME=/etc/inkchain/inkchain-ca-server
      - INKCHAIN_CA_SERVER_CA_CERTFILE=/etc/inkchain/inkchain-ca-server-config/ca.org1.example.com-cert.pem
      - INKCHAIN_CA_SERVER_CA_KEYFILE=/etc/inkchain/inkchain-ca-server-config/0e729224e8b3f31784c8a93c5b8ef6f4c1c91d9e6e577c45c33163609fe40011_sk
      - INKCHAIN_CA_SERVER_TLS_ENABLED=true
      - INKCHAIN_CA_SERVER_TLS_CERTFILE=/etc/inkchain/inkchain-ca-server-config/ca.org1.example.com-cert.pem
      - INKCHAIN_CA_SERVER_TLS_KEYFILE=/etc/inkchain/inkchain-ca-server-config/0e729224e8b3f31784c8a93c5b8ef6f4c1c91d9e6e577c45c33163609fe40011_sk
    ports:
      - "7054:7054"
    command: sh -c 'inkchain-ca-server start -b admin:adminpw -d'
    volumes:
      - ./channel/crypto-config/peerOrganizations/org1.example.com/ca/:/etc/inkchain/inkchain-ca-server-config
    container_name: ca_peerOrg1


  orderer.example.com:
    container_name: orderer.example.com
    image: inklabsfoundation/inkchain-orderer
    environment:
      - ORDERER_GENERAL_LOGLEVEL=debug
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/etc/inkchain/configtx/orderer.genesis.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/etc/inkchain/crypto/orderer/msp
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/etc/inkchain/crypto/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/etc/inkchain/crypto/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/etc/inkchain/crypto/orderer/tls/ca.crt, /etc/inkchain/crypto/peerOrg1/tls/ca.crt, /etc/inkchain/crypto/peerOrg2/tls/ca.crt]
    working_dir: /opt/gopath/src/github.com/inklabsfoundation/inkchain/orderers
    command: orderer
    ports:
      - 7050:7050
    volumes:
        - ./channel/genesis.block:/etc/inkchain/configtx/orderer.genesis.block
        - ./channel/crypto-config/ordererOrganizations/example.com/orderers/orderer.example.com/:/etc/inkchain/crypto/orderer
        - ./channel/crypto-config/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/:/etc/inkchain/crypto/peerOrg1
        - ./channel/crypto-config/peerOrganizations/org2.example.com/peers/peer0.org2.example.com/:/etc/inkchain/crypto/peerOrg2

  peer0.org1.example.com:
    container_name: peer0.org1.example.com
    extends:
      file:   base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.org1.example.com
      - CORE_PEER_LOCALMSPID=Org1MSP
      - CORE_PEER_ADDRESS=peer0.org1.example.com:7051
    ports:
      - 7051:7051
      - 7053:7053
    volumes:
        - ./channel/crypto-config/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/:/etc/inkchain/crypto/peer
    depends_on:
      - orderer.example.com

  peer1.org1.example.com:
    container_name: peer1.org1.example.com
    extends:
      file:   base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.org1.example.com
      - CORE_PEER_LOCALMSPID=Org1MSP
      - CORE_PEER_ADDRESS=peer1.org1.example.com:7051
    ports:
      - 7056:7051
      - 7058:7053
    volumes:
        - ./channel/crypto-config/peerOrganizations/org1.example.com/peers/peer1.org1.example.com/:/etc/inkchain/crypto/peer
    depends_on:
        - orderer.example.com

  peer0.org2.example.com:
    container_name: peer0.org2.example.com
    extends:
      file:   base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.org2.example.com
      - CORE_PEER_LOCALMSPID=Org2MSP
      - CORE_PEER_ADDRESS=peer0.org2.example.com:7051
    ports:
      - 8051:7051
      - 8053:7053
    volumes:
        - ./channel/crypto-config/peerOrganizations/org2.example.com/peers/peer0.org2.example.com/:/etc/inkchain/crypto/peer
    depends_on:
        - orderer.example.com

  peer1.org2.example.com:
    container_name: peer1.org2.example.com
    extends:
      file:   base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.org2.example.com
      - CORE_PEER_LOCALMSPID=Org2MSP
      - CORE_PEER_ADDRESS=peer1.org2.example.com:7051
    ports:
      - 8056:7051
      - 8058:7053
    volumes:
        - ./channel/crypto-config/peerOrganizations/org2.example.com/peers/peer1.org2.example.com/:/etc/inkchain/crypto/peer
    depends_on:
        - orderer.example.com

  cli:
    container_name: cli
    image: inklabsfoundation/inkchain-tools
    tty: true
    environment:
      #- GOPATH=/opt/gopath
      #- CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_LOGGING_LEVEL=DEBUG
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer0.org1.example.com:7051
      - CORE_PEER_LOCALMSPID=Org1MSP
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/inklabsfoundation/inkchain/peer/crypto/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/inklabsfoundation/inkchain/peer/crypto/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/inklabsfoundation/inkchain/peer/crypto/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/inklabsfoundation/inkchain/peer/crypto/peerOrganizations/org1.example.com/users/Admin@org1.example.com/msp
    working_dir: /opt/gopath/src/github.com/inklabsfoundation/inkchain/peer
    command: bash -c 'while true; do sleep 20171104; done'
    volumes:
        #- /var/run/:/host/var/run/
        - ../token:/opt/gopath/src/github.com/inklabsfoundation/inkchain/examples/chaincode/go/token
        - ../marbles:/opt/gopath/src/github.com/inklabsfoundation/inkchain/examples/chaincode/go/marbles
        - ./channel/crypto-config:/opt/gopath/src/github.com/inklabsfoundation/inkchain/peer/crypto/
        - ./scripts:/opt/gopath/src/github.com/inklabsfoundation/inkchain/peer/scripts/
        - ./channel/mychannel.tx:/opt/gopath/src/github.com/inklabsfoundation/inkchain/peer/channel-artifacts/mychannel.tx
    depends_on:
        - orderer.example.com
        - peer0.org1.example.com
    links:
      - orderer.example.com
      - peer0.org1.example.com
